class GameName 
{
    constructor(id: any, Name: string) 
    {
        id = 0o0;
        Name = "CodeAnEx: RaigaCross"
    }
}

function MainLoop(id: any, Name: string) 
{
    var n = "NewGame";
    var l = "LoadGame";
    var s = "Settings";
    var q = "Quit";
    var x = false;
    console.log(n +'\n', l+'\n', s+'\n', q);
    do 
    {

    } while (x == false);
    switch (x) 
    {
        case false:
            
            break;
    
        default:
            break;
    }
}